name: Release by tag
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Upgrade pip
        run: python -m pip install --upgrade pip -r requirements.txt

      - name: Install PyInstaller
        run: python -m pip install pyinstaller==5.9.0
      
      - name: Build and create zip file
        run: |
          .\release_by_tag.bat

      - name: Release
        uses: ncipollo/release-action@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract tag name
        id: extract_tag
        run: |
          $tag_name = $env:GITHUB_REF -replace "refs/tags/", ""
          $file_name = "Owl-${tag_name}.zip"
          Move-Item -Path ".\owl.zip" -Destination ".\${file_name}"
          Write-Output "file_name=$file_name" | Out-File -FilePath $env:GITHUB_OUTPUT -Append

      - name: Upload zip file
        id: upload-release-asset
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: ${{ steps.extract_tag.outputs.file_name }}
    